# Generated by Django 2.1.5 on 2019-01-13 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20190108_2101'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='explanation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='link',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
