# Generated by Django 2.1.5 on 2019-01-15 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_article_shabad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shabad',
            name='tags',
        ),
    ]
