# Generated by Django 2.0.9 on 2019-01-23 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20190119_2304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shabad',
            name='link',
            field=models.FileField(default='aa.mp3', upload_to=''),
            preserve_default=False,
        ),
    ]
