# Generated by Django 2.0.9 on 2019-04-27 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20190305_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='info',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
