# Generated by Django 2.0.9 on 2019-03-08 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20190308_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='absences',
            field=models.IntegerField(default=0),
        ),
    ]
